# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36ad12e51e7a7923ee8e62d2b6e3e12f23b4e50168491deca78043e48342eb8016e79404c81a0418e7de403b0b3a04d35537bb16a49dd8145267144b58d7fa05

test:
  secret_key_base: 8cd662fd88de5ae5d35c44ea13d04014addcb7ef08b98ffc6676a9f4f6d60fa15addc4ef81477f2360c59328bdc6f926376cd329675411e3cd883f108c22b911

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
